name: Publish
description: Publish to npm and jsr

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public

  publish-jsr:
    name: Publish to jsr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: npx jsr publish --config jsr.json
